[workspace]
members = ["ui"]

[workspace.dependencies]
console_error_panic_hook ={ version = "0.1.7", default-features = false }
leptos = { version = "0.7.4", default-features = false, features = ["csr"] }
serde = { version = "1.0.217", default-features = false }

workspace.resolver = "2"