[package]
name = "ui"
version = "0.1.0"
edition = "2021"
description = "The ui components of jwalk"

[dependencies]
console_error_panic_hook = { workspace = true }
csv = "1.3.1"
leptos = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
